encryption.key=b14ca5898a4e4133bbce2ea2315a1916
encryption.iv=1234567890123456
server.port=5218
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# SQL Server Database
spring.datasource.url=jdbc:sqlserver://192.168.70.14:1009;databaseName=BTI_OTCNew;encrypt=true;trustServerCertificate=true;loginTimeout=120
spring.datasource.username=DBcontroller
spring.datasource.password=DBcontroller@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=2

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
